### ISSUE TITLE
gocassa uses json tags to map to the struct names

### ISSUE THREAD

**Issue by 23inhouse** [gocassa/gocassa#103]
We found a bug that if you have json tags on a struct and you are reading from cassandra to the struct it will try to use the json tags as the struct field names.

For example gocassa will successfull write data to cassandra in the `foobar` field. When reading it will get caught up unmarshalling. It seems to try to write to the struct's `foo_bar` field which doesn't exist.

Example:

``` golang

type Example struct {
  FooBar string `json: "foo_bar"`
}
```

Here is the line of code that we think is causing the issue:
https://github.com/hailocab/gocassa/blob/master/op.go#L65

In your narrators humble opinion the expected behaviour would be to use the `cql` tags not the `json` tags.

**Comment by crufter** [comment]
You are right, unfortunately there is no easy way to get around this unless we can rewrite the struct tags with reflection... sounds terribly hacky.

**Comment by dancannon** [comment]
This should be fixed in the v1.0.0 release candidate.
