### ISSUE TITLE
New time series recipe

### ISSUE THREAD

**Issue by hailobackup** [gocassa/gocassa#11]
We need an other one time series recipe. One where we can store something in the time. It s a mix between one to may recipe and the actual time series recipe.

example.

create table areaEvent (
area city text,
bucket_t timestamp,
t timestamp,
uuid uuid,
value 1 blabla,
primary key ((area,bucket_t),t,uuid);

select area,t,value where area = 'LON' and bucket_t in(?) and t > 'XXX'

**Comment by jcampan** [comment]
its me
