### ISSUE TITLE
Recipes are somewhat special

### ISSUE THREAD

**Issue by crufter** [gocassa/gocassa#116]
See #115 

We should enable developers to roll their own, separate from gocassa.

**Comment by jcampan** [comment]
Should be nice to keep the recipes in Gocassa. 
My idea is when someone has a new use case, it can share it with all the other users of Gocassa. In this way the lib will be more and more useful .

**Comment by dancannon** [comment]
I have exported the `toMap` (now `ToMap`) function, I believe that this should allow third party developers to use their own recipes.

If you believe there are other changes required feel free to reopen the issue.
