### ISSUE TITLE
TimeSeries: let people specify their timestamp field, but save under a unified name internally

### ISSUE THREAD

**Issue by crufter** [gocassa/gocassa#13]
by @chrusty

**Comment by jcampan** [comment]
I dont agree with this point.  We should split internal recipe implementation and user needs.

**Comment by chrusty** [comment]
This does seem a bit crufty

**Comment by crufter** [comment]
Can we close this, then? @chrusty close it if you feel like, since you were the one who suggested this.

**Comment by crufter** [comment]
Closing this.
