### ISSUE TITLE
Order By wasn't supported?

### ISSUE THREAD

**Issue by ninhdhx** [gocassa/gocassa#137]
Is there any reason why we didn't support the "Order By"?
I can see the empty string return here https://github.com/hailocab/gocassa/blob/master/op.go#L176
and here https://github.com/hailocab/gocassa/blob/master/op.go#L156

**Comment by crufter** [comment]
@ninhdh0 

Query time orderby is inefficient (ie. specifying order at table creation and not changing it when querying is the way to go at scale), otherwise this could/should be implemented indeed.
Time to PR perhaps? : )
