### ISSUE TITLE
MockTable still uses json (un)marshalling, so does not support embed or non-key map types

### ISSUE THREAD

**Issue by ttqin** [gocassa/gocassa#138]
**gocassa/mock** is still using **encoding/json** marshalling/unmarshalling https://github.com/hailocab/gocassa/blob/master/mock.go#L472-L478

This is in contrast to the changes made to the implementation that uses the **gocassa/reflect** package and cql tags to remove reliance on encoding/json.

This means these types cannot be supported by the mock:
- embedded types
- map with non-string key types

The fix is probably to use the same marshalling/unmarshalling in these commits:
- **gocassa/reflect** - https://github.com/hailocab/gocassa/commit/d78293b16c7c51af51c013024c4ace1612653ca7
- **op.go** - https://github.com/hailocab/gocassa/commit/11b4111f2668d4f39045db9d2f21f26495ff60a1

Example test case:

``` go
type PostalCode string

type address struct {
       Time            time.Time
       Id              string
       LocationPrice   map[string]int       // json compatible map
       LocationHistory map[time.Time]string // not json compatible map
       PostCode        PostalCode           // embedded type
}

func TestEmbedMapTypesRead() {
       ks := NewMockKeySpace()
       tbl := ks.MapTable("addresses", "Id", address{})
       // insert some mock address data... 
       var actualAddress address
       err :=  tbl.Read("1", &actualAddress).Run())
       if err != nil {
             t.Fatalf("Could not read from mock map table: %v", err)
       }
}
```

should return you:

```
Could not read from mock map table: "json: unsupported type: map[time.Time]string"
```

**Comment by dancannon** [comment]
Fixed in v1.2.0
