### ISSUE TITLE
Document how batch request works

### ISSUE THREAD

**Issue by dancannon** [gocassa/gocassa#142]
This solution needs to be verified but something like this should work.

``` go
// Where batch is a slice of the items you want ot insert
op := gocassa.Noop()
for _, v := range batch {
    op = op.Add(table.Set(v))
}
err := op.Run()
```

**Comment by nascimj** [comment]
It does work, but it presents no performance gains. It is not a true "bulk" operation, as op.Run() simply loops through all the ops, calling Run() for each one. But then again, upon further reading on cassandra, it seems that bulk insert is not mean to improve performance as in a SQL db.

**Comment by crufter** [comment]
@nascimj You re right, actually it is more of a data integrity protection tool than a performance optimizing one. Logged batches are especially expensive in terms of performance. @jcampan can elaborate further.
