### ISSUE TITLE
Prefix or postfix tables by their type.

### ISSUE THREAD

**Issue by crufter** [gocassa/gocassa#15]
Also if the table is a timeseries table table name should contain bucket size

**Comment by jcampan** [comment]
prefix or postfix should be define by the user or hidden ?

**Comment by crufter** [comment]
Definitely hidden. This will enable users to use the same tablename with multiple recipes and let the library maintain the data in multiple tables.

**Comment by jcampan** [comment]
Sounds good to me.

**Comment by crufter** [comment]
Ok table names now contain table type, and important information like all the fields the table is 'parametrized over', ie:

```
keySpace.OneToManyTable("sale", "SellerId", "Id", Sale{})
```

Will result in table name: "sale_oneToMany_sellerid_id"\* while

```
keySpace.OneToManyTable("sale", "CustomerId", "Id", Sale{})
```

Will produce the table name: "sale_oneToMany_customerid_id"

*please ignore casing

**Comment by jcampan** [comment]
It s working.
