### ISSUE TITLE
Specify protocol version

### ISSUE THREAD

**Issue by damienrobson** [gocassa/gocassa#152]
I'm trying to use Gocassa against a 3.x installation of Cassandra and the keyspace connection fails because it wants to use Protocol Version 2, which doesn't work in 3.x. Is there a way to specify the underlying protocol version, or can this be added as an optional parameter when connecting?

**Comment by wienczny** [comment]
This bug is related to #146 

I'm using this code to connect to a 3.x server.

```
    DB := gocql.NewCluster(hosts...)
    DB.Keyspace = cassandraFlags.Keyspace
    DB.ProtoVersion = 4

    if len(cassandraFlags.Username) > 0 {
        DB.Authenticator = gocql.PasswordAuthenticator{
            Username: cassandraFlags.Username,
            Password: cassandraFlags.Password,
        }
    }

    var err error

    Session, err = DB.CreateSession()

    if err != nil {
        log.Fatal(err)
    }

    Connection := gocassa.NewConnection(gocassa.GoCQLSessionToQueryExecutor(Session))
```

**Comment by crufter** [comment]
Hi guys, @Skulmuk, @wienczny! 

There is a way to pass your own gocql session to gocassa:

https://godoc.org/github.com/hailocab/gocassa#NewConnection

Just get your own session with gocql and use https://godoc.org/github.com/hailocab/gocassa#GoCQLSessionToQueryExecutor to pass it to NewConnection.

Look at this for inspiration https://github.com/hailocab/gocassa/blob/master/gocql_backend.go#L72

Cheers!

**Comment by damienrobson** [comment]
Hi, @crufter! That's the same way in which I worked around the issue - I just thought it should probably be configurable via "native" gocassa option to save time.

**Comment by crufter** [comment]
@Skulmuk that's a great idea. I might look at implementing it
