### ISSUE TITLE
times series : the bucket doesn't have the good value

### ISSUE THREAD

**Issue by jcampan** [gocassa/gocassa#21]
package main

import (
//"fmt"
gocql "github.com/gocql/gocql"
c "github.com/hailocab/cmagic"
"time"
)

type Ts struct {
T          time.Time
InternalId gocql.UUID
RaceId    int
Fare      int
}

func main() {
// connect to a keyspace
k, err := c.ConnectToKeySpace("juju", []string{"127.0.0.1"}, "", "")
if err != nil {
panic(err)
}
//Debug mode
k.DebugMode(true)
// using a one to one table
times := k.TimeSeriesTable("ts", "T", "InternalId", time.Hour, Ts{})

if err != nil {
panic(err)
}
uuid, err := gocql.RandomUUID()
// writing a row
err = times.Set(Ts{
T:          time.Now(),
InternalId: uuid,
RaceId:    1,
Fare:      10,
})
if err != nil {
panic(err)
}

//read a row
//row, err := times.Read(timeStamp, "")
//fmt.Println(row)
}
Show less

INSERT INTO ts (t, internalid, raceid, fare, bucket) VALUES (?, ?, ?, ?, ?) [2015-01-19 13:33:27.723319424 +0000 GMT 70b517b6-d34e-4f7b-8339-280240364c15 1 10 1421672400]
 bucket                  | t                        | internalid                          | fare | raceid --------------------------+--------------------------+--------------------------------------+------+-------- 1970-01-17 11:54:32+0000 | 2015-01-19 13:33:27+0000 | 70b517b6-d34e-4f7b-8339-280240364c15 |  10 |      1
t

he bucket value is wrong

Should be  2015-01-19 13:00:00+0000

**Comment by crufter** [comment]
I think you created the table manually and you set bucket as timestamp, and I believe that is in microseconds in cassandra. I use int64 for the table schema and save only second precision.

Can you try this with having bucket as bigint in cassandra?
Alternatively, I can change the value to be microsecond precision not second.

**Comment by jcampan** [comment]
Timestamp type in cassandra is miliisecond precision. The cqlsh stuff is truncate the time to second for the read, but we dont care of it.

Internal timestamp are in microsecond, but it s something different.

**Comment by crufter** [comment]
Bucket technically doesn't have to be timestamp though. It can be int or string or whatever. However, since it represents a timestamp in the current implementation I agree it makes sense to make it an actual timestamp. Fixing it.

**Comment by jcampan** [comment]
It s working now
