### ISSUE TITLE
One to many : how te delete a complete row ? 

### ISSUE THREAD

**Issue by jcampan** [gocassa/gocassa#23]
The delete function it s asking for two value. Should be nice to be allow to give only the partition key when we need to delete the entire row.

races.Delete(1, 1) ==> delete a logical row
races.Delete(1,nil) ==> delete a physical row.

**Comment by crufter** [comment]
Maybe we could call it DeleteAll? Or MultiDelete?

**Comment by jcampan** [comment]
DeleteAll(id) sounds good to me

**Comment by jcampan** [comment]
adding label

**Comment by crufter** [comment]
Done.
