### ISSUE TITLE
Add TTL support for SET and UPDATE 

### ISSUE THREAD

**Issue by jcampan** [gocassa/gocassa#26]
TTL is awesome

**Comment by crufter** [comment]
Do you want per Set and per Update TTL or is it enough if we just have TTL for the whole table?

**Comment by jcampan** [comment]
I would like a TTL per queries, The library should not set metadata information.

**Comment by obeattie** [comment]
+1 for per-row TTLs.

**Comment by crufter** [comment]
Done.
