### ISSUE TITLE
timeseriesB : argument seems confusing for me

### ISSUE THREAD

**Issue by jcampan** [gocassa/gocassa#27]
for this struc 
type Benefits struct {
    T             time.Time
    InternalId    gocql.UUID
    City          string
    MinuteBalance int
}
the signature is : 
TimeSeriesBTable(tableName, timeField, fieldToIndexByField, uniqueKey, bucketSize, row)

 I need to create the table like that

 times := k.TimeSeriesBTable("benefits", "City", "T", "InternalId", time.Hour, Benefits{})

Seems strange, i was waiting for : 
times := k.TimeSeriesBTable("benefits", "T", "City", "InternalId", time.Hour, Benefits{})

It s a mistake ? let s talk on that tomorrow

**Comment by crufter** [comment]
Okay so this is completely up to us - I preferred the current order because it matches the OneToMany recipe which flows left to right from fields with lower cardinality to higher.

**Comment by jcampan** [comment]
Yes, but TimeFile is City in this example seems strange, we should maybe rename the parameters?

**Comment by crufter** [comment]
Indeed the naming was wrong in the interface definition. Fixed! Thanks!

**Comment by jcampan** [comment]
Fix
