### ISSUE TITLE
time series B list are calling too many bucket.

### ISSUE THREAD

**Issue by jcampan** [gocassa/gocassa#28]
Same problem than the time series

**Comment by crufter** [comment]
Do you mean we do not have a limit? Yes that is the care currently, it is trivial to add a limit though I will set it to ~200 for now is that ok?.

**Comment by jcampan** [comment]
no, i m saying that my query asking results  only one bucket and you are looking in two bucket

**Comment by crufter** [comment]
I see.

**Comment by jcampan** [comment]
it s working now
