### ISSUE TITLE
Give an []struct as argument for get or set method

### ISSUE THREAD

**Issue by jcampan** [gocassa/gocassa#30]
Should be nice ti be able to perform multi get or multi set.
We should speak about put a limit on it. like 100 ?

**Comment by crufter** [comment]
How does this interact with batching? Maybe the batching functionality will cover this?

**Comment by jcampan** [comment]
In a batch, you can query several tables, in a multi get for example you will call only one table.
The goal is to be able to have query like that : 
select \* from foo where id in (1,2,3,4,5) ;
 instead of
select \* from foo where id  =1 ;
select \* from foo where id  =2 ;
select \* from foo where id  =3 ;
select \* from foo where id  =4 ;
select \* from foo where id  =5 ;

It s going to be munch more faster.

**Comment by crufter** [comment]
MultiRead is already implemented. Multiple arguments for the Set is a subset of the batch functionality, so I am closing this.
