### ISSUE TITLE
Time series B : have more than one partition key.

### ISSUE THREAD

**Issue by jcampan** [gocassa/gocassa#32]
Is it hard to do it ?  the read and List need to handle an [] of partition key.

**Comment by crufter** [comment]
Not exceedingly hard. Can you include your use case here just so we develop the habit?

**Comment by jcampan** [comment]
CREATE TABLE benefits (
  city text,
  servicetype text,
  bucket timestamp,
  t timestamp,
  internalid uuid,
  minutebalance int,
  PRIMARY KEY ((city,servicetype, bucket), t, internalid)
) 

select \* from benefits where city= 'XXX' and service type = 'YYYY' and bucket in ( ?,? ?) and t >= xxx and T <= zzz ;

**Comment by jcampan** [comment]
Finally should be an other recipe if we need it
