### ISSUE TITLE
Library does not protect against injection attacks

### ISSUE THREAD

**Issue by obeattie** [gocassa/gocassa#33]
This library appears to generate queries [with string interpolation](https://github.com/hailocab/cmagic/blob/753e798b16968ba2bc0e9de6fffa687438fd9960/filter.go#L21). It seems to me that this method is vulnerable to injection attacks. From skimming [the `gocql` documentation](http://godoc.org/github.com/gocql/gocql#Session.Query), it looks like they support [bind variables](http://www.datastax.com/documentation/developer/java-driver/1.0/java-driver/quick_start/qsSimpleClientBoundStatements_t.html) to protect against this, which we should use.

**Comment by crufter** [comment]
Hey, @obeattie!

Thanks for joining the development! It is very much appreciated! Generally, this library does not use string interpolation, see https://github.com/hailocab/cmagic/blob/master/relation.go#L23 

The line you linked is concatenating pieces of CQL statements already using placeholders. The only exception to this is the keyspace and column family names in statement. If you do find examples where we do not use placeholders then it is a bug.

**Comment by obeattie** [comment]
Awesome. I thought it may be the case that I was missing something. I'll close this.
