### ISSUE TITLE
OneToManyTable returns struct pointers regardless of the declared type

### ISSUE THREAD

**Issue by obeattie** [gocassa/gocassa#50]
I'm using a `OneToManyTable`, which I've declared as so:

``` go
queriesTable = keyspace.OneToManyTable("queries", "Status", "Id", storedQuery{})
```

As you can see, the declared row type is `storedQuery`. However, when I call `List()` (and possibly other methods too), I get `*storedQuery` as the result type<sup>†</sup>:

``` go
panic: Unhandled response type: &dao.storedQuery{Q:"EVENT SEQ(a b);", Id:"0f32b15e-1cbc-402c-628b-be03bdb7f937", Status:0}
```

Is this expected behaviour?

† The panic is not in the gocassa library itself, but originates from a type switch I have in my service.

**Comment by crufter** [comment]
I think your expectation if returning the type with the same indirection is reasonable.
I believe currently all tables behave like this.

Fixing it.

**Comment by crufter** [comment]
This is applicable anymore, since because #44 related changes we don't return anything in reads anymore.
