### ISSUE TITLE
Consider decoupling statement generation and statement execution

### ISSUE THREAD

**Issue by obeattie** [gocassa/gocassa#51]
I think it's a bit weird that in order to use basically _any_ functionality in Gocassa, one has to be connected to Cassandra. The snippet in the README highlights this:

``` go
keySpace, err := gocassa.ConnectToKeySpace("test", []string{"127.0.0.1"}, "", "")
```

ie. getting a keyspace _object_ requires _connecting_ to that keyspace. In most ORMs, the query building logic is a completely separate layer to the query execution logic. ie. I can use most of the functionality of the ORM without ever being connected to the database. It's only at execution time that I need to obtain a connection. It would be great if we could consider the possibility of moving to that model with gocassa. I see the rationale as follows:
- When my service starts up, I don't necessarily immediately want to connect to Cassandra. Right now, most services will attempt to connect when a handler or other function is invoked that requires a connection. The current model seems to force me into a service panic when it starts up if it can't connect to C*
  
  I can get around this somewhat with an idempotent `connect()` function inside each data access method, that tries to setup the keyspaces/tables, but this doesn't feel like I should have to deal with this in my service code.
- For keyspace and table creation, I need to be able to get the CQL to execute without ever connecting to C*.
- I can see use-cases where I might want to see what CQL is going to be executed without ever executing it.
- I should be able to swap out the underlying connection at runtime for a mock or similar.

Anyway, I just wanted to put this here so we have a proper place to discuss the proposal and status.

---

Full HipChat conversation from yesterday:

> _Oliver Beattie:_ I'm a bit concerned about how being able to get a table or keyspace object is tied to having a Cassandra connection. Why is this? It seems to force us into a pattern of "if we can't connect to C*, the only option is to panic" which doesn't feel ideal. In most ORMs, the stuff that actually builds a query is a separate layer to the components that execute that query (ie. you can build a query without being connected).
> _John Worrell:_ true I suppose, but as soon as you try to execute it, then you get the panic
>         when you say "build a query"  I assume you mean make a string
> _Andreas Garnaes:_ I think creating the session could transparently be moved to where a query is actually being executed.
> _Oliver Beattie:_ i mean defining schema, and building the query (yes, the string, and its bind parameters)
>         the thing is, I don't want to have to panic
>         I want to be able to return an error (to requests), like we do now
>         usually you would decouple query building and query execution
>         this also means in the case of testing, you just replace/mock the connection itself, and the query building/data binding logic does not change
>         i can sort of get around it by having a connect() function that is idempotent, and called in all the data storage/retrieval methods, but it's crufty
>         i may also want to get a compiled CQL statement without executing it (which again should not require a connection to C*)
> _Andreas Garnaes:_ Moving session creation to execution time would allow returning errors. It would just be a matter of using keyspace.session() instead of keyspace.session. Wrt testing I'd prefer the current approach of in-memory Table instead anyway.
> _Andreas Garnaes:_ I see the point of separating CQL generation and execution, it just seems to complicate the interfaces (unnecessarily?).
> _Oliver Beattie:_ how is that?
> _Oliver Beattie:_ basically, i don't know anything of the internals, but that getting a keyspace means getting a connection, doesn't make sense to me
> _Andreas Garnaes:_ I think that's a good point which should be adressed.
> _Dafydd Woods:_ lol
> _Asim Aslam:_ +1 to separation of keyspace and connection logic. I also found this a bit weird. Think the interface needs to be more aligned with most database drivers.
> _Oliver Beattie:_ other use of this is for CQL schema creation: presumably we need a service to be able to report the CQL needed to create its schema without it having connected to a keyspace in the first place
>         which means that the schemas have to be defined before server.Run(), and it cannot depend on having a C* connection

**Comment by crufter** [comment]
Very good topic, thanks for initiating it, @obeattie 

Decoupling the query building and execution would be definitely a good idea, the only reason it is not done yet is because it is not done yet.

```
When my service starts up...
```

Would delaying connecting until it is actually required (what @andreas said) solve this?

```
For keyspace and table creation, I need to be able to get the CQL to execute without ever connecting to C*.
```

Keyspace and table creation (and drop) is supported, in fact tests show examples for both. See interfaces: https://github.com/hailocab/gocassa/blob/master/interfaces.go#L113 and https://github.com/hailocab/gocassa/blob/master/interfaces.go#L9.

I dislike the interface (inelegant) but the implementation is functional (keyspace creation is mostly for tests though due to the hardcoded replication settings).

```
I can see use-cases where I might want to see what CQL is going to be executed without ever executing it.
```

Makes sense.

```
I should be able to swap out the underlying connection at runtime for a mock or similar.
```

Not sure if that should be handled by the library

**Comment by obeattie** [comment]
I'm not sure how @andreas approach would work (in order to have a keyspace object in the first place, it seems I need a connection). In order for me to define my keyspace and table objects, which I assume are global objects, I need to have a connection. At the moment, I am doing this:

``` go
package dao

import (
    "sync"

    cassandra "github.com/hailocab/go-service-layer/gocassa"
    "github.com/hailocab/gocassa"
)

var (
    keyspace     gocassa.KeySpace
    keyspaceMtx  sync.RWMutex
    queriesTable gocassa.OneToManyTable
)

func setup() error {
    queriesTable = keyspace.OneToManyTable("queries", "Status", "Id", storedQuery{})
    return nil
}

func connect() error {
    keyspaceMtx.RLock()

    if keyspace == nil {
        keyspaceMtx.RUnlock()
        keyspaceMtx.Lock()
        defer keyspaceMtx.Unlock()

        if keyspace != nil { // Guard against race
            return nil
        } else if ks, err := cassandra.KeySpace(); err != nil {
            return err
        } else {
            keyspace = ks
            return setup()
        }
    } else {
        keyspaceMtx.RUnlock()
    }

    return nil
}
```

…and then, in each data access function, I am calling `connect()`.

**Comment by andreas** [comment]
To get a keyspace with gocassa, you currently call `ConnectToKeyspace(name, nodeIps, username, password) (KeySpace, error)`, which creates a session immediately. The bandaid to fix this would be to create the session lazily instead. Then we would replace `keyspace.session` with `keyspace.session()`, which would handle connecting at appropriate times. This is admittedly slightly crufty.

Other ideas:
- Attach a session to a keyspace.
- Pass session to set/update/delete/query.
- Use session to execute set/update/delete/query.

However we choose to solve this, I think it would be valuable to be able to keep the ability to replace `Table` with an in-memory representation and get mocking for that and all the other recipes for free.

**Comment by obeattie** [comment]
Not disagreeing that we should be able to swap out the `Table`, but I do think we should also be able to swap out the underlying connection. There are cases where I want to check the actual CQL being executed against my expectations (especially in cases where we may want to use hand-optimised CQL). It's just a case of having two layers of optional mocks.

I agree that perhaps this library should not handle any connection semantics: it would not be difficult for the caller to pass a connection to a gocassa `KeySpace` before executing statements. This allows total control over connection pooling etc. We (Hailo) could handle this transparently in the go-service-layer.

**Comment by crufter** [comment]
I think in cases where 'we may want to use hand-optimised CQL' we might want to simply fall back to gocql, instead of increasing the complexity of this library. We designed this library to be good for 80% of the use cases (as a start, to keep it simple), although I am happy to cover the remaining 20% if that does not complicate the matters for the users of the first 80%.

I also very much agree with @andreas 's approach of trying centering our attention at the underlying Table, because while that was initially a solution for mocking, mocking is a subset of your more generally worded problem; replacing the backend, @obeattie.

@obeattie your suggestion regarding passing the Connection to KeySpace is interesting.

Could we have a 'QueryExecuter' interface at one place in the code, which would be responsible for executing queries (even including managing connections)? That would be more or less be an answer to this thread.

Also, since we are revisiting the part where queries are being executed, this might be a good time to think about batching (#16) as well?

**Comment by obeattie** [comment]
> in cases where 'we may want to use hand-optimised CQL' we might want to simply fall back to gocql

That's exactly what I meant. What I was getting at, is that as things stand, the connection is completely hidden from the caller. It's currently impossible to fall back (because it's not possible to access/modify the session), without establishing a totally separate connection.

> Could we have a 'QueryExecuter' interface at one place in the code, which would be responsible for executing queries (even including managing connections)? That would be more or less be an answer to this thread.

Yes, that sounds like a great solution to me. Again, assuming that the caller can provide their own implementation of `QueryExecutor`. Presumably we can just make the connection pool in the go-service-layer implement this `QueryExecutor` interface. Profit. :smile:

**Comment by chrusty** [comment]
We need to ensure that all connections are managed by a pool. Constantly establishing new connections will slow us down. I'm guessing that this is why we need the keyspace object first.

Also for us the "table creation" is kind of irrelevant, as we're going to prevent any schema modifications in the LVE environment.

**Comment by obeattie** [comment]
It really seems as though the `QueryExecutor` approach works best. We need a connection pool, but it seems like what we have so far is a global connection (not in a pool). We have connection pooling in the service layer, making that implement the `QueryExecutor` interface @crufter proposes allows us to do pooling, and also addresses all my concerns (it separates statement generation and execution essentially, as the title requests).

**Comment by crufter** [comment]
Done.
