### ISSUE TITLE
Connection pool : Avoid to cross the Ocean

### ISSUE THREAD

**Issue by jcampan** [gocassa/gocassa#53]
Actually when we create the connection pool, we create a pool where we have all the nodes.(it s the auto discovery mode) 
We should have only the node from the same DC than the client in order to not cross the ocean.

We should do like in this example : https://github.com/gocql/gocql/blob/master/connectionpool.go

They can remove node from the connection pool.

**Comment by jcampan** [comment]
Apperently we can set the auto discovery to false, I will test it with Julien Da Silva.

**Comment by obeattie** [comment]
I'm migrating the actual connection logic to the go-service-layer. Open a ticket in JIRA if that implementation (when present) isn't satisfactory.
