### ISSUE TITLE
Note about link to gocassa from gocql

### ISSUE THREAD

**Issue by 0x6e6562** [gocassa/gocassa#73]
Great work in producing this library :-)

Since we maintain a list of binding options on the gocql README, I've added gocassa to this list.

This is just an FYI - feel free to close this issue straight away.

Also as an FYI - there is an ongoing discussion in gocql about layering should work in particular for data binding, this might be relevant for the work you are doing.

**Comment by crufter** [comment]
Hey, @0x6e6562

Thank you for the link, and thanks for gocql :-)! Where is that discussion exactly?

**Comment by jcampan** [comment]
Thanks a lot for your comment  :) and thank for the link

**Comment by 0x6e6562** [comment]
Sorry about taking so long to respond to this one. Basically the discussion spans multiple threads on the gocql mailing list and also multiple issues and pull requests in Github. Nobody has a cohesive thread about this because people interested in changing APIs are more concerned about specific functionality, whilst the maintenance team are just trying to respond with some kind of change management logic. Basically people want stuff to make their lives easier and the core team wants something that can remain robust and easy to maintain.
