### ISSUE TITLE
Consistency level defaults to ONE and is difficult to override

### ISSUE THREAD

**Issue by mattheath** [gocassa/gocassa#90]
The cluster consistency is set to `ONE` by default when creating a new gocql backend here:
https://github.com/hailocab/gocassa/blob/ebff9ff045fa0c728d6a3f2830a6fa17867c0587/gocql_backend.go#L42-L44
- It's not documented anywhere
- To replace this, the user must provide a whole new `QueryExecutor` which is very inconvienient
- The inline documentation explicitly states that the `QueryExecutor` should only be replaced for mocking or testing purposes [here](https://github.com/hailocab/gocassa/blob/f228afbf9beee9599af9136b4716edf9d4bcb299/interfaces.go#L172-L174)
- The default in gocql is `Quorum`

**Comment by crufter** [comment]
Fair points, @mattheath 

This part of the library is a bit neglected - we rolled our own `QueryExecutor` for a number of reasons. It is probably the best place to detach gocassa from the fiddly low level details though, so I think the solution is to make it easy to create a `QueryExecutor` if one has a gocql.Cluster/Session.

I will come back with a more detailed reply soon.

**Comment by crufter** [comment]
#94 fixed this.
