### ISSUE TITLE
Cannot delete rows from tables with custom TableName

### ISSUE THREAD

**Issue by davidzhao** [gocassa/gocassa#91]
I have a table `files` with partition key `hash`. gocassa is configured with the TableName option:

```
options := gocassa.Options{
  TableName: "files",
}
table := keyspace.Table("files", &File{}, keys).WithOptions(options)
```

When deleting a row using gocassa it gives the following error. Insertion and updates on the same table work fine.

```
unconfigured columnfamily files__hash
```

**Comment by davidzhao** [comment]
Looks like in op.go, generateWrite isn't using the custom table name. I'll submit a pull request.

**Comment by davidzhao** [comment]
this fix resolves the issue for me; it's pretty straight forward. let me know if you see any issues with it before merging.

**Comment by crufter** [comment]
Thank you, David!
