### ISSUE TITLE
Why tables are suffixed by partitionKeys and ClusteringColumns

### ISSUE THREAD

**Issue by thoas** [gocassa/gocassa#95]
see [here](https://github.com/hailocab/gocassa/blob/master/keyspace.go#L34)

What are the design reasons to do that?

**Comment by crufter** [comment]
Hey, @thoas 

The idea was that one can use different kind of tables (eg. map, multimap etc) with the same table name (eg. "customers"), since often one has the same data saved multiple times to allow for different queries.

Instead of making people manually name their tables (ie. "customersByDepartment", "customersById" etc), gocassa does it.

There are also some future plans to support syncing data across such "same data, saved for different indices/queries" tables, and having the tables named in a certain way may prove helpful.

If you dislike the default table names, use the `Options` type to override it.

Let's not close this ticket until this is explained in the readme.

**Comment by thoas** [comment]
allright :)

I have seen the option to override it, I'm not a big fan of implicit names but I respect your decision, thank you for the explanation.

I have implemented [nullable field](https://github.com/thoas/gocassa/commit/19d60ded178b0e95ac52717a8156cf42a7f8631b).

I'm using them in my models with uuid fields to avoid `00000000-0000-0000-0000-000000000000` as default value, are you interested by this feature?

**Comment by crufter** [comment]
That definitely looks like an interesting feature, I will have a look at the code, can you make a PR?
Can you write a test case for it?

**Comment by thoas** [comment]
Ok :)

I will send you a PR with tests when it will be ready.

**Comment by crufter** [comment]
great! : )

**Comment by thoas** [comment]
Before sending you a PR (I have to write additional tests also).

Could you take some time on your side to look at my [changes](https://github.com/hailocab/gocassa/compare/master...thoas:refactoring)?

Here is what I have done:
- Removed all panic in the codebase, I prefer to send the err to the parent method
- Implemented the nullable fields in StructInfo
- Refactored the `toMap` mechanism

I know, it's a lot of changes on your side so tell me what do you want :)

**Comment by obeattie** [comment]
This caught my eye in my feed so thought I would share my 2¢.

I am not in favour of removing all `panic`s. For instance, I think the `Table` setup code is okay to panic (I'm bound to catch it that way), and there isn't a huge amount one could do programatically to mitigate an unrecognised row type. I could see having to do an `if err != nil` dance all over the place when setting up tables being really annoying.

I do however, agree _some_ `panic`s could be eliminated. For instance, the ones [during `Op` construction](https://github.com/hailocab/gocassa/compare/master...thoas:master#diff-978eaa6c07bfff36f52e2325a0697e30L15). I think a good idea here could be to store the `error`s on an `Op` internally until `Run()` is called, and return them then. This preserves the chainability of `Op`s and removes the `panics`s.

**Comment by thoas** [comment]
nice idea :+1: 

I agree with you, removing panic in some parts involve writing more code in some cases.

I will separate my code and propose you only a PR for nullable fields (with tests of course) and then remove the panic (I'm also open to a code proposal).

**Comment by sjwhitworth** [comment]
Go best practice says that panics within external libraries are usually classified as bugs. However, I disagree - I think it's good to panic when initialising things. Being unable to setup/initialise some data storage is most likely going to be a non recoverable error, and you should bail hard at the quickest possible opportunity.  When querying however, I wouldn't panic in any form - just return the `err`

**Comment by crufter** [comment]
@obeattie Agreed on all points.
